# -*- coding: utf-8 -*-
"""Titanic Analysis and Prediction Classification

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/#fileId=https%3A//storage.googleapis.com/kaggle-colab-exported-notebooks/titanic-analysis-and-prediction-classification-1b5c0716-ec8b-4ada-b9ac-bab2130a15b1.ipynb%3FX-Goog-Algorithm%3DGOOG4-RSA-SHA256%26X-Goog-Credential%3Dgcp-kaggle-com%2540kaggle-161607.iam.gserviceaccount.com/20240925/auto/storage/goog4_request%26X-Goog-Date%3D20240925T174312Z%26X-Goog-Expires%3D259200%26X-Goog-SignedHeaders%3Dhost%26X-Goog-Signature%3Da56020d933bde243e10fae75e66547a61b72db511b60383606589b2f9e5bae74c5f3d3806bdb72ec7d63ad2670ac0ec2b0b32621f5cfe4f3dcac8b32ae44952329da2d3653bfaebd50b7638c41f2a9df9f2e8b76b33cfcab488a93b70339d10b653ad20a41ac9f245ad0f4335036654732abf1a54f67cada058c6e2fe286ad7c1425c7917f89d3963ce8fd3f55d539fbd79d7494351c1b68fe0d8f8242223c915de01b5ba7ceb818ab2c6baceb7ca0cf86e6935c4214483ed47f01ce7f1b40fd012832dfdd49c9fa5174aa2e04b1b4c5a4c1b80f0bf12a32a3036c763f084e6849b10c4a0ab6d1ce211cb351453a44331ea5f79e472a648d22998df346694402
"""

import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.preprocessing import MinMaxScaler, LabelEncoder,StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC

df=pd.read_csv('/kaggle/input/titanic-dataset/Titanic-Dataset.csv')

df.head(10)

df.info()

df.isnull().sum()

"""- There is alot of null values within the table so we will remove the cabin column and we will remove the null rows of age because age is an essential factor and remove the null values of embarked"""

df.drop(['Cabin'], axis=1,inplace=True)

"""- Dropped Cabin Column because too many null values"""

df.dropna(inplace=True)

df.info()

"""- Now there is no null values"""

df.duplicated().sum()

"""- There is no Duplicates Values

# UniVariate Analysis

### Survived Column
"""

survived_counts = df['Survived'].value_counts()
survived_counts

plt.figure(figsize=(8, 6))
plt.pie(survived_counts, labels=['No', 'Yes'], autopct='%1.1f%%', colors=['#FF9999', '#66B2FF'], startangle=90)
plt.title('Survival Proportion')
plt.show()

plt.figure(figsize=(8, 6))
sns.barplot(x=survived_counts.index, y=survived_counts.values, palette='viridis')
plt.title('Survival Count')
plt.xlabel('Survived (1 = Yes, 0 = No)')
plt.ylabel('Number of Passengers')
plt.xticks([0, 1], ['No', 'Yes'])
plt.show()

"""- More People Died than Survived

### Pclass Column
"""

df['Pclass'].value_counts()

sns.barplot(x=[1,2,3],y=df['Pclass'].value_counts(),palette='viridis')
plt.title("Ticket Class Count")
plt.ylabel('Number of tickets')
plt.xlabel('Ticket Class')
plt.show()

"""- Most of the tickets were first Class and second and third class people were nearly the same count

### Sex Column
"""

df.Sex.value_counts()

sns.barplot(x=['Male','Female'],y=df.Sex.value_counts(),palette='viridis')
plt.title("Gender Table")
plt.xlabel('Gender Type')
plt.ylabel('Gender Count')
plt.show()

"""- More Male than Female where on the ship

### Age Column
"""

df.Age.describe()

sns.histplot(x=df['Age'],bins=20)
plt.title("Age Distribution Table")
plt.xlabel("Age")
plt.ylabel('Age Count')
plt.show()

"""- Most ages were from 20 to 30 years but there was a lot of babies too

### SibSp column
"""

df.SibSp.value_counts()

sns.barplot(x=['0','1','2','3','4','5'],y=df.SibSp.value_counts(),palette='viridis')

"""- Most people were alone/ had no siblings on the Ship

### Parch Column
"""

df.Parch.value_counts()

sns.barplot(x=['0','1','2','3','4','5','6'],y=df.Parch.value_counts(),palette='viridis')

"""- Most People had no Parents/ Children on the ship

### Fare Column
"""

df.Fare.describe()

sns.histplot(df['Fare'], bins=20)
plt.title("Fare Distribution")
plt.xlabel("Fare")
plt.ylabel("Fair Price")

"""- The most fare from 0 to 100 but there is alot of outliers so we must detect the outliers

#### Detecting Outliers
"""

Q1= df['Fare'].quantile(0.25)
Q3=df['Fare'].quantile(0.75)

IQR=Q3-Q1

upper=Q3 + 1.5*IQR
Lower=Q1 - 1.5*IQR

print(upper)
print(Lower)

"""- There is alot of upper outliers and we are going to point them out"""

df[df["Fare"]>70]

"""- There are 95 People that paid higher than average amount of Fare which can be understood because people who paid alot more than average may be because they reserved later and so on

### Embarked Column
"""

Embarked_counts=df['Embarked'].value_counts()
Embarked_counts

sns.barplot(x=['S','C','Q'],y=Embarked_counts,palette='viridis')

"""# Multi Variate Analysis"""

df.groupby(['Sex'])['Survived'].value_counts()

"""- Alot more Males Died than Females because at this instances males priotize women to survive than men
- More Men Died than Survived
- More Female Survived than Died
"""

df.groupby(['Pclass'])['Survived'].value_counts()

"""- Most People Died from Class 3 because this was the closest to the ocean
- People from Class 1 where the most ones survived as they were the highest from the ocean and they were priotized to get on boats
- People from Class 2 where almost 50/50 to survive
"""

df.groupby(['Pclass','Sex'])['Survived'].value_counts()

"""- Least men died where from Class 1 and only 3 women died from class 1
- Most men and women died where from Class 3
- The only Class that more Females Died than Survived where in Class 1
- The least percantage of men that died where on Class 1

- This Concludes that Class 1 was the most priotized and safest place on the Ship
"""

bins = [0, 18, 35, 50, 65, float('inf')]
labels = ['0-18', '19-35', '36-50', '51-65', '66+']
df['AgeGroup'] = pd.cut(df['Age'], bins=bins, labels=labels, right=False)

df[df['Survived']==0].groupby(['AgeGroup'])['Survived'].value_counts()

"""- Most people died were from ages 19-35 after it people from ages 36-50"""

df.groupby(['AgeGroup','Sex'])['Survived'].value_counts()

df.groupby(['SibSp'])['Survived'].value_counts()

df.groupby(['Parch'])['Survived'].value_counts()

"""# Machine Learning

### Logistic Regression

#### Preproccessing
"""

df.info()

df.corr(numeric_only=True)

df.drop(['PassengerId','Ticket','Name','AgeGroup'],axis=1,inplace=True)

df.head()

encoder= LabelEncoder()
df['Sex']=encoder.fit_transform(df['Sex'])
df['Embarked']=encoder.fit_transform(df['Embarked'])
df['Survived']=encoder.fit_transform(df['Survived'])

X=df.drop(columns=["Survived"])
y=df.Survived

X

y

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,shuffle=True,random_state=7)

model=LogisticRegression(max_iter=12000)
model.fit(X_train,y_train)

y_pred=model.predict(X_test)

model.score(X_train,y_train)*100

model.score(X_test,y_test)*100

rate=accuracy_score(y_test,y_pred)*100
print(f'{int(rate)}%')

print(classification_report(y_test,y_pred))

print(confusion_matrix(y_test,y_pred))

"""### SVC"""

modelsv=SVC()
modelsv.fit(X_train,y_train)

y_pred=modelsv.predict(X_test)

modelsv.score(X_train,y_train)*100

modelsv.score(X_test,y_test)*100

rate=accuracy_score(y_test,y_pred)*100
print(f'{int(rate)}%')

"""## KNN Classifier"""

ModelK=KNeighborsClassifier(n_neighbors=12)
ModelK.fit(X_train,y_train)

y_pred=ModelK.predict(X_test)

ModelK.score(X_train,y_train)*100

ModelK.score(X_test,y_test)*100

rate=accuracy_score(y_test,y_pred)*100
print(f'{int(rate)}%')

print(classification_report(y_test,y_pred))

print(confusion_matrix(y_test,y_pred))

"""## Decision Tree Classifier"""

classifier=DecisionTreeClassifier()
classifier.fit(X_train,y_train)

y_pred=classifier.predict(X_test)

print(classifier.score(X_train,y_train)*100)

print(classifier.score(X_test,y_test)*100)

print(accuracy_score(y_test,y_pred)*100)

